repos:
  - repo: https://github.com/haiiliin/pofmt
    rev: "65a58de8fa0f2f7b1551413692ead86d994aecce"
    hooks:
      - id: pofmt
        additional_dependencies: ["pangu"] # for handling Chinese documents

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.2"
    hooks:
      - id: prettier
