repos:
  - repo: https://github.com/frostming/pofmt
    rev: "0.4.0"
    hooks:
      - id: pofmt
        additional_dependencies: ["pangu"] # for handling Chinese documents

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.2"
    hooks:
      - id: prettier
