repos:
  - repo: https://github.com/haiiliin/pofmt
    rev: "65a58de8fa0f2f7b1551413692ead86d994aecce"
    hooks:
      - id: pofmt
        additional_dependencies: ["pangu"] # for handling Chinese documents
        args:
          - --line-length=88
