files:
  - source: /**/pot/**/*.pot
    ignore:
      - /**/pot/reference/**/*.pot
      - /**/pot/user/**/*.pot
      - /**/pot/CHANGES.pot
    translation: /**/%locale_with_underscore%/LC_MESSAGES/**/%file_name%.po
