files:
  - source: "/**/pot/*.pot"
    translation: "/**/%locale_with_underscore%/LC_MESSAGES/%file_name%.po"
    ignore:
      - "/**/pot/CHANGES.pot"
  - source: "/**/pot/**/*.pot"
    translation: "/**/%locale_with_underscore%/LC_MESSAGES/**/%file_name%.po"
    ignore:
      - "/**/pot/reference/**/*.pot"
      - "/**/pot/user/**/*.pot"
